### ISSUE TITLE
add packages to class

### ISSUE THREAD

**Issue by helmut2** [MFOberwolfach/SNAPSHOTS#86]
könntest Du bitte bei der nächsten Klassenversion das Paket mathtools mit einbinden, das wir regelmäßig hinzuladen.

Könntest Du bitte die Pakete trackchanges und wrapfig noch einbinden? trackchanges gibt es hier: trackchanges.sf.net

**Comment by wasserverein** [comment]
Hi, thanks for posting this. However, I don't get who receives these messages. Helmut, did you write something as a note for yourself? Then maybe I'm not supposed to even see this?

Regarding trackchanges, I made a slightly modified version that doesn't interfere with the Snapshots footnote style. If you are interested in using it, I can send you a pull request.

**Comment by helmut2** [comment]
done
